//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentItem
    {
        public int Id { get; set; }
        public int KalaId { get; set; }
        public int DocumentId { get; set; }
        public int Amount { get; set; }
        public string Description { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual Kala Kala { get; set; }
    }
}
